### ISSUE TITLE
Server crashing on start up

### ISSUE THREAD

**Issue by Scratchman** [Baijson/SimplyJuices#2]
I'm not having any problems using this mod in single player but it's crashing the server on start up.

[https://pastebin.com/Lj2HmY2Z](https://pastebin.com/Lj2HmY2Z)

Thanks for creating this mod, we really need something like this in 1.10.2.

**Comment by Baijson** [comment]
Seems like an issue in Skeleton. Will be fixed within an hour or so.

Thanks!

**Comment by Baijson** [comment]
Updating Skeleton to 1.0.1 should resolve the issue.
