### ISSUE TITLE
Request, Option to change food points and saturation

### ISSUE THREAD

**Issue by Scratchman** [Baijson/SimplyJuices#3]
I love the mod but I wanted to make things a bit more difficult for my players and have changed the recipes to require 6 berries per bottle of juice.

We have Spice of Life on the server so I'd like to balance the harder recipes with a cfg option to increase the food and saturation points of the juices, this can only be done with the mod the food comes from.

Thanks

**Comment by Baijson** [comment]
Someone actually asked me the same thing last night.

Will add this in the next update!

**Comment by Scratchman** [comment]
awesome, thanks baijson :)

**Comment by Baijson** [comment]
Added and uploaded to Curse. 
Uploads were approved, so expect it to be on the launcher within 30 minutes or so.

youre welcome ;)
