### ISSUE TITLE
1.7.10 backport pls

### ISSUE THREAD

**Issue by m1jordanallen** [Baijson/SimplyJuices#5]
STOP BEING LAZY AND  DOOOOO EEEEET

**Comment by Baijson** [comment]
No.

**Comment by m1jordanallen** [comment]
y u close my report?  At least read it. Stop being lazy

**Comment by Baijson** [comment]
i'm not kidding Jordan, i am not backporting it. 


Pancake. <3

**Comment by m1jordanallen** [comment]
Good, people still deving in 1.7.10 need to let go and move on :P

**Comment by Baijson** [comment]
My reason for not backporting, is because i dont want to maintain a fuckton of branches, for every version of minecraft. :)
